config/routes.rb
AppName::Application.routes.draw do

  devise_for :reviewers
  resources :reviewers
  resources :jobs
  

  root 'jobs#index'

end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :reviewer


  yearFormatValidation = /\d{4}/

  # validations
  validates :company, presence: true
  validates :role, presence: true
  validates :startyear, presence: true, format: {with: yearFormatValidation}, length: {is: 4}
  validates :endyear, format: {with: yearFormatValidation}, allow_blank: true, length: {is: 4}


end

app/models/reviewer.rb
class Reviewer < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # validations
  validates :name, presence: true
  validates :location, presence: true


end

app/models/temp_jobs.rb
class Job < ActiveRecord::Base
  belongs_to :reviewer
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:name, :email, :password, :password_confirmation, :location) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:name, :email, :password, :password_confirmation, :location, :current_password) }
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def new
    @job = Job.new
  end

  def create

  	@job = Job.new(job_params)

    if @job.reviewer_id != current_reviewer.id
      redirect_to root_path
    else
      if @job.save
        redirect_to jobs_path
      else
        render 'new'
      end
    end
  end

  def index
  	@jobs = Job.all
    @reviewers = Reviewer.all
  end

  def edit
    @job = Job.find(params[:id])
  end

  def update
    @job = Job.find(params[:id])

    if @job.reviewer_id != current_reviewer.id
      render 'edit'
    else
      if @job.update(params[:job].permit(:company, :role, :startyear, :endyear, :reviewer_id))
        redirect_to jobs_path
      else
        render 'edit'
      end
    end
  end

  def show
    @job = Job.find(params[:id])
  end

  def job_params
  	params.require(:job).permit(:company, :role, :startyear, :endyear, :reviewer_id)
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    redirect_to jobs_path
  end

end

app/controllers/reviewers_controller.rb
class ReviewersController < ApplicationController
  def new
  	@reviewer = Reviewer.new
  end

  def create
  	@reviewer = Reviewer.new(reviewer_params)
  	if @reviewer.save
  		redirect_to reviewers_path
  	else
  		render 'new'
	end
  end

  def reviewer_params
  	params.require(:reviewer).permit(:name, :location, :email)
  end

  def index
  	@reviewers = Reviewer.all
  end

  def edit
    @reviewer = Reviewer.find(params[:id])
  end

  def show
    @reviewer = Reviewer.find(params[:id])
    @jobs = Job.all
  end

  def update
    @reviewer = Reviewer.find(params[:id])

    if @reviewer.update(params[:reviewer].permit(:name, :location, :email))
      redirect_to reviewers_path
    else
      render 'edit'
    end
  end

  def destroy
    @reviewer = Reviewer.find(params[:id])
    @reviewer.destroy

    redirect_to reviewers_path
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/reviewers_helper.rb
module ReviewersHelper
end

app/views/jobs/edit.html.erb
<div class="error-msg">
  <% if @job.errors.any? %>
  <ul>
    <% @job.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
  <% end %>
</div>

<%= form_for :job, url: job_path(@job), method: :patch do |f| %>

  <p>
    <%= f.label :company %><br>
    <%= f.text_field :company %>
  </p>
 
  <p>
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </p>

  <p>
    <%= f.label :startyear %><br>
    <%= f.number_field :startyear %>
  </p>

  <p>
    <%= f.label :endyear %><br>
    <%= f.number_field :endyear %>
  </p>

<!--
  <p>
  	<%= f.label :reviewer_id %><br>
  	<%= f.collection_select :reviewer_id, Reviewer.all, :id, :name%>
  </p>
-->

  <p>
    <%= f.hidden_field :reviewer_id, :value => current_reviewer.id %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h1>REVIEWER DATABASE</h1>

<table>
	<tr>
		<td>REVIEWER</td>
		<td>COMPANY</td>
		<td>ROLE</td>
		<td>START YEAR</td>
		<td>END YEAR</td>
	</tr>
	<% @reviewers.each do |currentreviewer| %>
	<tr>
		<td><%= link_to currentreviewer.name, reviewer_path(currentreviewer.id) %></td>
		<% @jobs.each do |job| %>
			<tr>
			<% if job.reviewer != nil && job.reviewer == currentreviewer %>
			<td></td>
			<td><%= job.company %></td>
			<td><%= job.role %></td>
			<td><%= job.startyear %></td>
			<td><%= job.endyear %></td>
				<%if reviewer_signed_in? %>
					<% if job.reviewer.id == current_reviewer.id %>
						<td><%= link_to 'Edit', edit_job_path(job) %></td>
						<td><%= link_to 'Delete', job_path(job), method: :delete, data: {confirm: 'Are you sure?'} %></td>
					<% end %>
				<% end %>
			<% end %>
			</tr>
		<% end %>
	</tr>
	<%end%>
</table>

app/views/jobs/new.html.erb
<div class="error-msg">
	<% if @job.errors.any? %>
	<ul>
		<% @job.errors.full_messages.each do |msg| %>
		<li><%= msg %></li>
		<% end %>
	</ul>
	<% end %>
</div>

<%= form_for(@job) do |f| %>

	<div class="field">
		<p>company</p>
		<%= f.text_field :company%>
	</div>

	<div class="field">
		<p>role</p>
		<%= f.text_field :role%>
	</div>

	<div class="field">
		<p>start year</p>
		<%= f.number_field :startyear%>
	</div>

	<div class="field">
		<p>end year</p>
		<%= f.number_field :endyear%>
	</div>

	<div class="field">
		<%= f.hidden_field :reviewer_id, :value => current_reviewer.id %>
	</div>

	<div class="actions">
		<%= f.submit %>
	</div>

<% end %>

app/views/jobs/show.html.erb
<h3><%= @job.company %> - <%= @job.role %></h3>
<p><%= @job.startyear %> to <%= @job.endyear %></h3>
<p>Reviewer: <%= @job.reviewer.name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AppName</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<div class="navbar">
		<ul class="nav">
			<li class='dropdown'><a class="nav-link" href="#">Reviewers</a>

			</li>
			<li class='dropdown'><a class="nav-link" href="#">Jobs</a>
				<ul>
					<li><%= link_to "New Jobs", new_job_path %></li>
					<li><%= link_to "All Jobs", jobs_path %></li>
				</ul>
			</li>
			<% if !reviewer_signed_in? %>
			<li>
				<%= link_to 'Login', new_reviewer_session_path, :class => "nav-link" %>
			</li>
			<% else %>
			<li>
				<%= link_to 'Edit Profile', edit_reviewer_registration_path, :class => "nav-link" %>
			</li>
			<li>
				<%= link_to 'Logout', destroy_reviewer_session_path, :method => :delete, :class => "nav-link" %>
			</li>
			<% end %>

		</ul>
	</div>


	<p class="notice"><%= notice %></p>
	<p class="alert"><%= alert %></p>

	<div class="content">
		<%= yield %>
	</div>

</body>
</html>

app/views/reviewers/delete.html.erb
<h1>Reviewers#delete</h1>
<p>Find me in app/views/reviewers/delete.html.erb</p>

app/views/reviewers/edit.html.erb
<%= form_for :reviewer, url: reviewer_path(@reviewer), method: :patch do |f| %>

  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </p>

  <p>
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
 
<%= link_to 'Back', reviewers_path %>

app/views/reviewers/index.html.erb
<h1>REVIEWER INFORMATION</h1>

<table>
	<tr>
		<td>NAME</td>
		<td>LOCATION</td>
		<td>EMAIL</td>
		<th></th>
	</tr>
	<% @reviewers.each do |reviewer| %>
	<tr>
		<% if reviewer != nil %>
		<td><%= link_to reviewer.name, reviewer_path(reviewer.id) %></td>
		<td><%= reviewer.location %></td>
		<td><%= reviewer.email %></td>
		<td><%= link_to 'Edit', edit_reviewer_path(reviewer) %></td>
		<td><%= link_to 'Delete', reviewer_path(reviewer), method: :delete, data: {confirm: 'Are you sure?'} %></td>
		<% end %>
	</tr>
	<% end %>
</table>

app/views/reviewers/new.html.erb
<%= form_for(@reviewer) do |f| %>
	<div class="field">
		<p>name</p>
		<%= f.text_field :name%>
	</div>
	<div class="field">
		<p>location</p>
		<%= f.text_field :location%>
	</div>
	<div class="field">
		<p>email</p>
		<%= f.text_field :email%>
	</div>
	<div class="actions">
		<%= f.submit %>
	</div>
<% end %>

app/views/reviewers/show.html.erb
<h2><%= @reviewer.name %></h2>
<p><%= @reviewer.email %></p>
<p><%= @reviewer.location %></p>


<table>
	<tr>
		<td>COMPANY</td>
		<td>ROLE</td>
		<td>START YEAR</td>
		<td>END YEAR</td>
	</tr>
	<% @jobs.each do |job| %>
	<tr>
		<% if job.reviewer == @reviewer %>
		<td><%= job.company %></td>
		<td><%= job.role %></td>
		<td><%= job.startyear %></td>
		<td><%= job.endyear %></td>
		<%end%>
	</tr>
	<%end%>
</table>